### ISSUE TITLE
[FEATURE] Support Laravel 11

### ISSUE THREAD

**Issue by jschram** [cyberwolf-studio/lingua#14]
While upgrading a project to Laravel 11, I noticed that this package didn't support it yet.
I've created a pull request to add support: https://github.com/cyberwolf-studio/lingua/pull/13

**Comment by jschram** [comment]
Hi @mikield, thanks for merging my PR!

Could you also please tag a new version of this package so composer can require it in the normal way?

**Comment by mikield** [comment]
@jschram yes, sorry have forgotten to do that.
New `v0.9.6` was released.

**Comment by jschram** [comment]
Thanks! However, it seems you have tagged a previous version (same commit hash as v0.9.5) as the new version:
![image](https://github.com/cyberwolf-studio/lingua/assets/10851379/619028b4-2dd1-43de-8425-8b5712992902)

**Comment by mikield** [comment]
Sorry, my mistake. I have pushed `v0.9.61` with the right changes.

**Comment by jschram** [comment]
No problem, thanks again!
