### ISSUE TITLE
How to change locale?

### ISSUE THREAD

**Issue by brouwersron** [cyberwolf-studio/lingua#6]
Everything works flawlessly, I just cannot figure out how to change the locale? How do I use this?

const setLocale = inject('setLocale')
setLocale(locale)

I am using laravel so in my middleware I am forwarding the locale, so it should be simple but I cannot figure it out

**Comment by mikield** [comment]
Locale changes should be handled by Laravel itself.
So if you want to change your user's locale - just do that like in any other Laravel application.

This Vue.JS method exists only to change displayable locale on the fly.
So if you use that into your `setup` function - it should update your locale at client side and display translations in new locale.

**Comment by brouwersron** [comment]
Thanks, I think I am just too noob with vue stuff.. last question about this. For example, you mean something like this?

<script setup>
import {inject} from "vue";

const setLocale = inject('setLocale')
setLocale(locale)
</script>

This is telling me: Unresolved variable or type locale. Any working example or I should figure that out on my own? :)

**Comment by mikield** [comment]
You do not need to set locale inside your `setup` method.
If you set this package right - it should get that from `HandleInertiaRequests` middleware.

**Comment by brouwersron** [comment]
Alright, thanks a lot, I figured it out now!!

**Comment by brouwersron** [comment]
Actually, I thought I figured it out, but I don't. I have setup the package right. Everything works. However, when changing the locale, only the strings that are translated server side are being translated. Everything translated in my vue components stays on the initial locale. Of course when I refresh the page, it works.

The translations from both languages are there. Showing a welcome message in my default layout like so:

{{ __('phrases.welcome') }}

I am however, using this package: https://github.com/mcamara/laravel-localization

And to update the locale server side I have a simple route:

Route::get('lang/{language}', function ($language) {
    Session()->put('locale', $language);
    return redirect()->route('user.dashboard');
});

**Comment by mikield** [comment]
I do not understand what do you mean by 

> verything translated in my vue components stays on the initial locale.

How do you manage your translations?
Could you provide some repo with example of your problem?

**Comment by mikield** [comment]
Ok, I will have a look at that.

JFYI: 
` {{ __('phrases.welcome') }}` is using package translate function, that loads translations from `resources/js/lignua.js` file.
`{{ welcome }}` is sent from Laravel that uses Laravel's translate function, and gets translations from `lang` folder of your projekt (Lingua generates an `.js` file based on contents of that folder)

**Comment by brouwersron** [comment]
Yep, I understand, and it is generating everything nicely. I just wanted to show the "issue". Perhaps the issue is me though :)

After changing the locale, and then after doing a page refresh, it works though

**Comment by mikield** [comment]
Ok, that's strange that after refresh it works :)

Cause I noticed an error with that example.
I do replace somewhere too much, and as result we have that content in `lingua.js` file:

```js
const Lingua = {
    translations: {
        "en": {
            "php": {
                "phrases": {
                    "welcome": "Welcome"
                }
            },
            "json": []
        },
        "es": {
            "php": {
                "phras": "phras"
            },
            "json": []
        }
    }
}

export {
    Lingua
}
```

As you can see `phras` is clipped, and I think it has something to do with `es` as locale.
Will test it with another locale, and fix that case, maybe that will fix your case too.

**Comment by mikield** [comment]
Ok, I have pushed [v0.9.36](https://github.com/cyberwolf-studio/lingua/releases/tag/v0.9.36) hot fix version that fixes that issue.

Please upgrade, regenerate your `lingua.js` file using `php artisan lingua:generate` and let me know if the issue persist.

**Comment by brouwersron** [comment]
Looks good, nice and fast hotfix :)

But you said it's strange that after a refresh for me it works. It's because I am using 'en' and 'nl' locale, my apologies. I was using 'es' as an example, because I used it in my previous website.

Seems for, at least me, the locale is not changed on the js side after changing it server side. I don't know how to debug this actually, otherwise I could perhaps provide some more info.

**Comment by mikield** [comment]
I have pushed that test project that I was using while trying to reproduce your issue.
[mikield/test-lingua](https://github.com/mikield/test-lingua)

Please try to reproduce your issue there, and I will be able to pull your changes and see what's happening.

**Comment by brouwersron** [comment]
Thanks, when I get home tonight I will simply use that project you made locally and see if that works "out of the box" so to speak and if so, then this issue is fixed because it was me that was the issue. But if not, I'll let you know too :)

**Comment by brouwersron** [comment]
So I've added or changed some things to show the issue as minimal as possible. It does not work for me locally, but perhaps you can see what I might be doing wrong.

**Comment by mikield** [comment]
Try to upgrade to [v0.9.40](https://github.com/cyberwolf-studio/lingua/releases/tag/v0.9.40) this issue should be fixed.

But it brought some changes that should be addressed here:
1) No more `setLocale` function.
2) No need to pass `locale` into your `app.js` file.
